name: Deploy Lambda Functions and Static Assets

on:
  push:
    branches:
      - 'main'
    paths:
      - 'fetch_subscriptions.py'
      - 'oauth_start.py'
      - 'oauth_callback.py'
      - 'utils.py'
      - 'static/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy-lambdas:
    if: ${{ !cancelled() && 'pull_request' != github.event_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - fetch_subscriptions
          - oauth_start
          - oauth_callback

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Determine Lambda function name
        id: set_lambda_name
        run: |
          if [ "${{ matrix.function }}" = "fetch_subscriptions" ]; then
            echo "lambda_name=${{ secrets.LAMBDA_FETCH_NAME }}" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.function }}" = "oauth_start" ]; then
            echo "lambda_name=${{ secrets.LAMBDA_START_NAME }}" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.function }}" = "oauth_callback" ]; then
            echo "lambda_name=${{ secrets.LAMBDA_CALLBACK_NAME }}" >> $GITHUB_OUTPUT
          fi

      - name: Deploy ${{ matrix.function }}
        run: |
          zip ${{ matrix.function }}.zip ${{ matrix.function }}.py utils.py
          aws lambda update-function-code \
            --function-name "${{ steps.set_lambda_name.outputs.lambda_name }}" \
            --zip-file "fileb://${{ matrix.function }}.zip"

  upload-assets:
    needs: deploy-lambdas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload static assets to S3
        run: |
          aws s3 cp static/ s3://$S3_BUCKET_NAME/ --recursive
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

      - name: Invalidate CloudFront cache # Force privacypolicy.html page to refresh upon push
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/privacypolicy.html"
