name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  push:
    branches:
      - 'test-*'
      - 'test/*'

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install uv
      - name: Check with ruff
        continue-on-error: false
        run: |
          target_version='py310'
          ignore_csv_list='E701,E722,E731'
          {
              echo '## Output from `ruff check`'
              echo ''
              echo '### Formats'
              echo ''
              for fmt in full concise grouped pylint
              do
              echo '<details>'
              echo '<summary>'"${fmt}"'</summary>'
              echo ''
              echo '#### '"${fmt}"' output format'
              echo ''
              echo '```'
              uvx --no-config --no-progress --isolated \
                  ruff check --exit-zero \
                  --target-version "${target_version}" \
                  --output-format "${fmt}" \
                  --extend-select RUF100 \
                  --ignore "${ignore_csv_list}"
              echo ''
              echo '```'
              echo ''
              echo '</details>'
              echo ''
              done
          } >> "${GITHUB_STEP_SUMMARY}"
          uvx --no-config --no-progress --isolated \
              ruff check \
              --target-version "${target_version}" \
              --output-format github \
              --ignore "${ignore_csv_list}"

    
